name: Debug Docker Hub Credentials

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Docker Hub credentials
        run: |
          echo "Checking if secrets are set..."
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "DOCKER_USERNAME is set"
          else
            echo "DOCKER_USERNAME is NOT set"
          fi
          
          if [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "DOCKER_PASSWORD is set"
          else
            echo "DOCKER_PASSWORD is NOT set"
          fi
          
          echo "Repository name will be: ${{ secrets.DOCKER_USERNAME }}/spamassassin-mcp"
          
          # Check if the repository exists by trying to access it
          echo "Testing with curl (this won't actually work without proper auth, but shows the URL structure)"
          echo "Repository URL: https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/spamassassin-mcp/"

      - name: Test Docker Hub login
        run: |
          # This is just a test to see if we can authenticate
          # We won't actually use docker login in the real workflow
          echo "Testing authentication concept..."
          echo "Note: We can't actually test Docker Hub login here without exposing credentials"