name: Final Docker Hub Update

on:
  workflow_dispatch:

jobs:
  update-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Docker Hub information
        run: |
          chmod +x scripts/extract-dockerhub-info.sh
          ./scripts/extract-dockerhub-info.sh

      - name: Show that files exist
        run: |
          ls -la dockerhub-overview.md
          echo "First 5 lines:"
          head -5 dockerhub-overview.md

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/spamassassin-mcp
          short-description: "A secure, containerized Model Context Protocol (MCP) server"
          readme-filepath: ./dockerhub-overview.md