name: Test Docker Hub No Condition

on:
  workflow_dispatch:

jobs:
  update-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Docker Hub information
        run: |
          chmod +x scripts/extract-dockerhub-info.sh
          ./scripts/extract-dockerhub-info.sh

      - name: Show that files exist
        run: |
          ls -la dockerhub-overview.md
          echo "First 5 lines:"
          head -5 dockerhub-overview.md

      - name: Debug secrets
        run: |
          echo "DOCKER_USERNAME is set: ${{ secrets.DOCKER_USERNAME != '' }}"
          echo "DOCKER_PASSWORD is set: ${{ secrets.DOCKER_PASSWORD != '' }}"
          # Show length of short description (max 100 chars for DockerHub)
          DESC="A secure, containerized Model Context Protocol (MCP) server that integrates SpamAssassin"
          echo "Short description length: ${#DESC}"

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/spamassassin-mcp
          short-description: "A secure, containerized Model Context Protocol (MCP) server"
          readme-filepath: ./dockerhub-overview.md