name: Test Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: spamassassin-mcp:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          # Run the container in the background
          docker run -d --name test-container -p 9090:8080 spamassassin-mcp:test
          
          # Wait for the container to start
          sleep 10
          
          # Check if the container is running
          if docker ps | grep -q test-container; then
            echo "Container is running successfully"
          else
            echo "Container failed to start"
            docker logs test-container
            exit 1
          fi
          
          # Clean up
          docker stop test-container
          docker rm test-container