name: Test Docker Hub Update

on:
  workflow_dispatch:

jobs:
  test-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create simple Docker Hub overview
        run: |
          echo "# Test Docker Hub Overview" > dockerhub-test.md
          echo "This is a test overview for the spamassassin-mcp repository." >> dockerhub-test.md

      - name: Update Docker Hub description
        if: secrets.DOCKER_USERNAME != ''
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/spamassassin-mcp
          short-description: "Test description for spamassassin-mcp"
          readme-filepath: ./dockerhub-test.md