name: Test External Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test with a different action
        uses: actions/setup-node@v3
        with:
          node-version: '18'